name: main
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4.1.1

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 20
          registry-url: "https://npm.pkg.github.com"
          scope: "@octocat"

      - name: Npm install
        run: npm ci

      - name: ESLint
        uses: actions/checkout@v2
        with:
          repository: github/eslint-action
          ref: v2

      - name: Run Typecheck
        run: npx tsc --noEmit

      - name: Run tests
        run: |
          npm run test
          mkdir -p coverage
          mv ./coverage ./coverage-report
          echo "coverage-report" >> .gitignore

  publish-gpr:
    needs: test
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          registry-url: https://npm.pkg.github.com/
      - run: npm ci
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.ACTION_TOKEN}}
##
