name: main
on: push

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout Repo
        uses: actions/checkout@v4.1.1
      - name: Setup node
        uses: actions/setup-node@v4.0.2
        with:
          node-version: 20
      - name: Npm install
        run: npm ci
      - name: Run tests
        run: npm run test
